enable_disqus: false
enable_analytics: false
highlighter: rouge
permalink: pretty

#_url: http://localhost:4000
#_url: https://flaviomicheletti.github.io/html-canvas
_url: http://www.devfuria.com.br/html-canvas

secao: html-canvas

defaults:
  -
    scope:
      path: ""
    values:
      layout: "artigo"
